@echo off
md "App\QQ"
md "App\QQNT"
md "App\TIM"
md "App\WeChat"
md "Data\Common Files"
md "Data\Documents\Tencent"
md "Data\Documents\WeChat"
md "Data\Roaming\Tencent"
md "Data\Roaming\WeChat"
md "Data\SysWOW64"
md "Desktop"
md "Scripts"
